### ISSUE TITLE
能否说明那些动画可以上商店？

### ISSUE THREAD

**Issue by zhw511006** [lizelu/CATransitionDemo#1]
如题，谢谢！

**Comment by leewaycn** [comment]
不可以的。

**Comment by lizelu** [comment]
关于CoreAnimation私有API的问题是很常见的问题，调用私有API通过审核的可能很小，该Demo中使用了好多private api中的type, 如下：

NSString *const kCATransitionCube = @"cube";  
NSString *const kCATransitionSuckEffect = @"suckEffect"; 
NSString *const kCATransitionOglFlip = @"oglFlip";  
NSString *const kCATransitionRippleEffect = @"rippleEffect";  
NSString *const kCATransitionPageCurl = @"pageCurl"; 
NSString *const kCATransitionPageUnCurl = @"pageUnCurl";   
NSString *const kCATransitionCameraIrisHollowOpen = @"cameraIrisHollowOpen";
NSString *const kCATransitionCameraIrisHollowClose = @"cameraIrisHollowClose";

**Comment by zhw511006** [comment]
非常感谢！
