### ISSUE TITLE
没有说明使用了私有API，一切都没意义，自己玩是可以的。认真你就输了。

### ISSUE THREAD

**Issue by leewaycn** [lizelu/CATransitionDemo#3]
没有说明使用了私有API，一切都没意义，自己玩是可以的。认真你就输了。

**Comment by lizelu** [comment]
这很明显一看就调用了私有API吗，还是得声明一下：

Public API ：
// CAAnimation.h

/* Common transition types. */

CA_EXTERN NSString * const kCATransitionFade
    __OSX_AVAILABLE_STARTING (__MAC_10_5, __IPHONE_2_0);
CA_EXTERN NSString * const kCATransitionMoveIn
    __OSX_AVAILABLE_STARTING (__MAC_10_5, __IPHONE_2_0);
CA_EXTERN NSString * const kCATransitionPush
    __OSX_AVAILABLE_STARTING (__MAC_10_5, __IPHONE_2_0);
CA_EXTERN NSString * const kCATransitionReveal
    __OSX_AVAILABLE_STARTING (__MAC_10_5, __IPHONE_2_0);

其他直接调用的效果就是私有APIle
